### ISSUE TITLE
Review AWS Config conformance pack results

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5175]
We need a list of non-compliant rules in any account that don't already have a corresponding SecurityHub finding. I think the names of the rules in the latter set all start with `securityhub-`. For each rule in that list we need the account name, the rule description and, ideally, a list of non-compliant resources. Convert that list to Markdown using the following template and insert it as a comment here so that we can triage them more easily.

```
- [ ] {rule_name}
  - Triage result: 
  - Description: {rule_description}
  - Accounts:
    - {account_name_1}
    - …
  - Resources:
    - {resource_name_1}
    - …
- [ ] …
```
